env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  indent: [error, tab]
  no-tabs: 0
  object-curly-spacing: [1, never]
  no-unused-vars: [ 2, {
          "varsIgnorePattern": "should|expect"
        }
      ]
