env:
  browser: true
  es2021: true
  mocha: true
extends:
  - standard
parserOptions:
  ecmaVersion: 2020
  sourceType: module
rules:
  comma-dangle: [0]
  indent: [error, tab]
  no-tabs: 0
  operator-linebreak: [2, never]
  space-before-function-paren: [2, never]
  object-curly-spacing: [1, never]
  no-unused-vars: [ 2, {
    "varsIgnorePattern": "should|expect"
  }]
